export const ADD_TODO = "ADD_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const EDIT_TODO_TITLE = "EDIT_TODO_TITLE";

export const TOGGLE_COMPLETED_STATUS = "TOGGLE_COMPLETED_STATUS";
export const TOGGLE_EDITING_STATUS = "TOGGLE_EDITING_STATUS";

export const REMOVE_COMPLETED_TODOS = "REMOVE_COMPLETED_TODOS";
