name: Create new version and deploy to Now

on:
  push:
    branches:
      - release/*.*.*

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test
      env:
        CI: true
  
  create_new_version:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version and Branch name
        id: version_branch_name
        run: |
          echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=VERSION::`echo ${GITHUB_REF#refs/*/} | awk 'match($0,/[0-9]+.[0-9]+.[0-9]+/) {print substr($0, RSTART, RLENGTH)}'`
      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Create New Version
        id: create_new_version
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

          git pull

          npm config set git-tag-version false
          npm version ${{ steps.version_branch_name.outputs.VERSION }}

          git add -u
          git commit -m "Incremented version number to ${{ steps.version_branch_name.outputs.VERSION }}"
          
          git checkout master
          git merge --no-ff ${{ steps.version_branch_name.outputs.BRANCH_NAME }}
          git push origin master
          
          git tag -a ${{ steps.version_branch_name.outputs.VERSION }} -m "Releasing ${{ steps.version_branch_name.outputs.VERSION }}"
          git push origin ${{ steps.version_branch_name.outputs.VERSION }}
          
          git push --delete origin ${{ steps.version_branch_name.outputs.BRANCH_NAME }}
          git branch -D ${{ steps.version_branch_name.outputs.BRANCH_NAME }}

  deploy_to_now:
    needs: [ unit_tests, create_new_version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Now
        id: now
        uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID}}
          now-project-id: ${{ secrets.PROJECT_ID}} 

  lighthouse_check:
    needs: [ unit_tests, create_new_version, deploy_to_now ]
    runs-on: ubuntu-latest
    steps:
    - name: Audit live URL
      uses: jakejarvis/lighthouse-action@master
      with:
        url: ${{ steps.now.outputs.preview-url }}
    - name: Upload results as an artifact
      uses: actions/upload-artifact@master
      with:
        name: report
        path: './report'