name: Deploy to Now

on:
  push:
    branches:
      - release/*.*.*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm test
      env:
        CI: true
  
  version:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=BRANCH_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=VERSION::`echo ${GITHUB_REF#refs/*/} | awk 'match($0,/[0-9]+.[0-9]+.[0-9]+/) {print substr($0, RSTART, RLENGTH)}'`
      - name: Version
        id: version
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          npm config set git-tag-version false
          npm version ${{ steps.branch_name.outputs.VERSION }}
          git add -u
          git commit -m "Incremented version number to ${{ steps.branch_name.outputs.VERSION }}"
          git checkout master
          git merge --no-ff ${{ steps.branch_name.outputs.BRANCH_NAME }}
      - run: |
          git push origin master
          git tag -a ${{ steps.branch_name.outputs.VERSION }} -m "Releasing ${{ steps.branch_name.outputs.VERSION }}"
          git push origin ${{ steps.branch_name.outputs.VERSION }}
          git push --delete origin ${{ steps.branch_name.outputs.SOURCE_NAME }}
          git branch -D ${{ steps.branch_name.outputs.SOURCE_NAME }}


  deploy:
    needs: [ test, version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Now
        id: now
        uses: amondnet/now-deployment@v2
        with:
          zeit-token: ${{ secrets.ZEIT_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          now-org-id: ${{ secrets.ORG_ID}}
          now-project-id: ${{ secrets.PROJECT_ID}} 